api:
  dashboard: true
  debug: true
entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
serversTransport:
  insecureSkipVerify: true
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /config.yml
certificatesResolvers:
  vercel:
    acme:
      storage: "{{ traefik_data_directory }}/data/acme.json"
      dnsChallenge:
        provider: vercel
        resolvers:
          - "76.76.21.21:53"
          