---
- name: Create Plex Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ plex_config_directory }}"
    - "{{ plex_logs }}"

- name: plex Docker Container
  docker_container:
    name: plex
    image: linuxserver/plex
    pull: true
    #networks:
    # - proxy
    volumes:
      - "{{ plex_config_directory }}:/config:rw"
      - "{{ plex_logs }}:/opt/plex/Library/Application Support/Plex Media Server/Logs:rw"
      - "{{ plex_movies_directory }}:/movies:{{ plex_movies_permissions }}"
      - "{{ plex_tv_directory }}:/tv:{{ plex_tv_permissions }}"
      - "{{ plex_photos_directory }}:/photos:{{ plex_photos_permissions }}"
      - "{{ plex_podcasts_directory }}:/podcasts:{{ plex_podcasts_permissions }}"
      - "{{ plex_music_directory }}:/music:{{ plex_music_permissions }}"
      - "{{ plex_audiobooks_directory }}:/audiobooks:{{ plex_audiobooks_permissions }}"
    network_mode: "host"
    devices: "{{ plex_devices | default(omit) }}"
    env:
      TZ: "{{ timezone }}"
      PUID: "{{ plex_user_id }}"
      PGID: "{{ plex_group_id }}"
      VERSION: "{{ plex_version }}"
    restart_policy: unless-stopped
    #labels:
    # - "traefik.enable=true"
    # - "traefik.http.routers.plex.entrypoints=http"
    # - "traefik.http.routers.plex.rule=Host(`plex.local.atahankucuk.com`)"
    # - "traefik.http.middlewares.plex-https-redirect.redirectscheme.scheme=https"
    # - "traefik.http.routers.plex.middlewares=plex-https-redirect"
    # - "traefik.http.routers.plex-secure.entrypoints=https"
    # - "traefik.http.routers.plex-secure.rule=Host(`plex.local.atahankucuk.com`)"
    # - "traefik.http.routers.plex-secure.tls=true"
    # - "traefik.http.routers.plex-secure.service=plex"
    # - "traefik.http.services.plex.loadbalancer.server.port=32400"
    # - "traefik.docker.network=proxy"

#- name: docker proxy network
# docker_network:
#   name: proxy
#   internal: no