---

- name: Install mergerfs
  apt:
    name: mergerfs
    state: present
    update_cache: yes
  
- name: Mount the data drives
  mount:
    name: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: ext4
    state: mounted
    passno: "2"
  with_items: "{{ disks }}"
  when: disks[0] is defined
  
- name: Mount the parity drives
  mount:
    name: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: ext4
    state: mounted
    passno: "2"
  with_items: "{{ parity_disks }}"
  when: parity_disks[0] is defined


- name: Mount the mergerfs array
  mount:
    name: "{{ mergerfs_root }}"
    src: /mnt/data*
    opts: direct_io,defaults,allow_other,moveonenospc=1,minfreespace=100G,fsname=mergerfs,uid=1000,gid=1000
    fstype: fuse.mergerfs
    state: mounted
  when: disks[0] is defined

