---
- name: Create Portainer Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ portainer_data_directory }}"

- name: Portainer Docker Container
  docker_container:
    name: portainer
    image: portainer/portainer-ce
    pull: true
    #networks:
    # - proxy
    volumes:
      - "{{ portainer_data_directory }}:/data:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - "{{ portainer_port }}:9000"
    restart_policy: unless-stopped
    #labels:
    # - "traefik.enable=true"
    # - "traefik.http.routers.portainer.entrypoints=http"
    # - "traefik.http.routers.portainer.rule=Host(`portainer.local.atahankucuk.com`)"
    # - "traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme=https"
    # - "traefik.http.routers.portainer.middlewares=portainer-https-redirect"
    # - "traefik.http.routers.portainer-secure.entrypoints=https"
    # - "traefik.http.routers.portainer-secure.rule=Host(`portainer.local.atahankucuk.com`)"
    # - "traefik.http.routers.portainer-secure.tls=true"
    # - "traefik.http.routers.portainer-secure.service=portainer"
    # - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    # - "traefik.docker.network=proxy"

#- name: docker proxy network
# docker_network:
#   name: proxy
#   internal: no