---
- name: Create Heimdall group
  group:
    name: heimdall
    gid: "{{ heimdall_group_id }}"
    state: present

- name: Create Heimdall user
  user:
    name: heimdall
    uid: "{{ heimdall_user_id }}"
    state: present
    system: yes
    update_password: on_create
    create_home: no
    group: heimdall

- name: Create Heimdall Directories
  file:
    path: "{{ item }}"
    state: directory
    owner: heimdall
    group: heimdall
  with_items:
    - "{{ heimdall_data_directory }}"

- name: Create Heimdall container
  docker_container:
    name: heimdall
    image: "{{ heimdall_docker_image }}"
    pull: true
    #networks:
    # - proxy
    volumes:
      - "{{ heimdall_data_directory }}:/config:rw"
    env:
      PUID: "{{ heimdall_user_id }}"
      PGID: "{{ heimdall_group_id }}"
      TZ: "{{ timezone }}"
    ports:
      - "{{ heimdall_port_http }}:80"
      - "{{ heimdall_port_https }}:443"
    restart_policy: unless-stopped
    #labels:
    # - "traefik.enable=true"
    # - "traefik.http.routers.heimdall.entrypoints=http"
    # - "traefik.http.routers.heimdall.rule=Host(`heimdall.local.atahankucuk.com`)"
    # - "traefik.http.middlewares.heimdall-https-redirect.redirectscheme.scheme=https"
    # - "traefik.http.routers.heimdall.middlewares=heimdall-https-redirect"
    # - "traefik.http.routers.heimdall-secure.entrypoints=https"
    # - "traefik.http.routers.heimdall-secure.rule=Host(`heimdall.local.atahankucuk.com`)"
    # - "traefik.http.routers.heimdall-secure.tls=true"
    # - "traefik.http.routers.heimdall-secure.service=heimdall"
    # - "traefik.http.services.heimdall.loadbalancer.server.port=1080"
    # - "traefik.docker.network=proxy"

#- name: docker proxy network
# docker_network:
#   name: proxy
#   internal: no