---
- name: Create Radarr Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ radarr_data_directory }}"

- name: Radarr
  docker_container:
    name: radarr
    image: linuxserver/radarr
    pull: true
    #networks:
    # - proxy
    volumes:
      - "{{ radarr_movies_directory }}:/movies:rw"
      - "{{ radarr_download_directory }}:/downloads:rw"
      - "{{ radarr_data_directory }}:/config:rw"
    ports:
      - "{{ radarr_port }}:7878"
    env:
      TZ: "{{ timezone }}"
      PUID: "{{ radarr_user_id }}"
      PGID: "{{ radarr_group_id }}"
    restart_policy: unless-stopped
    #labels:
    # - "traefik.enable=true"
    # - "traefik.http.routers.radarr.entrypoints=http"
    # - "traefik.http.routers.radarr.rule=Host(`radarr.local.atahankucuk.com`)"
    # - "traefik.http.middlewares.radarr-https-redirect.redirectscheme.scheme=https"
    # - "traefik.http.routers.radarr.middlewares=radarr-https-redirect"
    # - "traefik.http.routers.radarr-secure.entrypoints=https"
    # - "traefik.http.routers.radarr-secure.rule=Host(`radarr.local.atahankucuk.com`)"
    # - "traefik.http.routers.radarr-secure.tls=true"
    #- "traefik.http.routers.radarr-secure.service=radarr"
    # - "traefik.http.services.radarr.loadbalancer.server.port=7878"
    # - "traefik.docker.network=proxy"

#- name: docker proxy network
# docker_network:
#   name: proxy
#   internal: no